### ISSUE TITLE
Issues with pages routes with new shopify session system

### ISSUE THREAD

**Issue by aurelienbobenrieth** [Shopify/koa-shopify-auth#104]
I've been trying to rework an app to use the new session auth system.
Everything seems to work fine, however I am not able to use the `Navigation` ([polaris][1]) component successfully.

Let's say I have something like this : 
```javascript
<Navigation.Section
    items={[
        {
            url : '/faq',
            label : translations.faq,
            icon : HintMajor
        }
    ]}
/>
```

If I only put `/faq` I am unable to access the route. I am redirected to `/auth` and get obviously an error.

The only way I manage to make my routes work is to : 

1. Add the shop query in each url like this : 
```javascript
// ...
url : '/faq?shop=${shop}',
// ...
```

2. Add every needed routes manually in my `server.js` WITHOUT the `verifyRequest` middleware (which does not seem like a good option to me)
```javascript
// ...
router.get('/faq', handleRequest)
// ...
```

Can someone explain if I am doing anything wrong ?
(I am managing my SESSION_STORAGE with the custom redis storage shown in the repo doc https://github.com/Shopify/shopify-node-api/blob/main/docs/usage/customsessions.md)

  [1]: https://polaris.shopify.com/components/navigation/navigation

**Comment by aurelienbobenrieth** [comment]
And I am unable to navigate through my pages without the whole page reloading. 

For example, if I use : 
````
import { useRouter } from 'next/router'
// ...
const router = useRouter()

const updateRoute = (route) => {
    router.push(route)
}
// ...
updateRoute('/faq?shop=${shop}')
```

The whole page will reload.

I am not getting it.

**Comment by andyjgao** [comment]
+1 on this error I have this problem as well, was wondering if there's any workarounds for this?
