### ISSUE TITLE
[Koa-shopify-auth] missing "/" in redirect url when passing prefix

### ISSUE THREAD

**Issue by barrypeng6** [Shopify/koa-shopify-auth#13]
## Overview
If passing prefix `/shopify`
```javascript
app.use(
  shopifyAuth({
    prefix: '/shopify',
    apiKey: SHOPIFY_API_KEY,
    secret: SHOPIFY_SECRET,
    scopes: ['write_orders, write_products'],
    accessMode: 'offline',
    afterAuth(ctx) {
      // do something...
    },
  }),
);
```
Expected redirect URL should be `/shopify/auth/enable_cookies?shop=test.myshopify.com`, but the result is `/shopifyauth/enable_cookies?shop=test.myshopify.com`

Should add `/` between `prefix` and `auth` of URL
```javascript
doesNotHaveStorageAccessUrl: "${prefix}/auth/enable_cookies?shop=${encodeURIComponent(
  shop,
)}",
```
https://github.com/Shopify/quilt/blob/master/packages/koa-shopify-auth/src/auth/client/request-storage-access.ts#L10

**Comment by sirrodgepodge** [comment]
fixed this in the mirror of this repo here:
https://github.com/Shopify/quilt/pull/1620

**Comment by devjones** [comment]
Just seeing this issue.  Another PR submitted here:
https://github.com/Shopify/koa-shopify-auth/pull/29
