### ISSUE TITLE
API Deprecation Notice from metafields API call

### ISSUE THREAD

**Issue by unreact-kohiki** [Shopify/koa-shopify-auth#138]
# Issue summary
Hello!
I am getting the following warning in my logs even though my app is not using the deprecated API "metafields.valueType".
I'm not sure where to find the code that causes this warning.

log:

```
API Deprecation Notice: {
 message: 'https://shopify.dev/changelog/online-store-2-0-new-metafields-type-system-and-dynamic-sources',
 path: 'https://shop-name.myshopify.com/admin/api/2021-10/metafields.json?limit=1'
}
```

## Expected behavior
My app is not using the deprecated API, so we shouldn't see this notification in the log.

## Actual behavior
Notifications about deprecated APIs will be displayed in the log.

log:

```
API Deprecation Notice: {
 message: 'https://shopify.dev/changelog/online-store-2-0-new-metafields-type-system-and-dynamic-sources',
 path: 'https://shop-name.myshopify.com/admin/api/2021-10/metafields.json?limit=1'
}
```

I clicked on "path" and got the following screen.
I see an object with the key "metafields" and an empty array for the value.

![Image from Gyazo](https://i.gyazo.com/a9a4c501c5b1fac01f0b1f4dfe3232ad.png)

## Additional Information

- "@shopify/koa-shopify-auth": "^4.1.4"
- "@shopify/shopify-api": "^1.2.1",

**Comment by aldoalprak** [comment]
This issue has been more than 6 months, but there is no news from the contributor. You can refer to this thread #118

**Comment by TheSecurityDev** [comment]
I've just created a simpler version of this library (that fixes this and other issues), which you can find at https://www.npmjs.com/package/simple-koa-shopify-auth
