### ISSUE TITLE
[koa-shopify-auth] verifyToken perhaps should use GET not POST

### ISSUE THREAD

**Issue by kavika-1** [Shopify/koa-shopify-auth#14]
## Overview

Was stepping through the redirect paths and noticed verify-token.ts fetch always returns 400, not 401 or 200.  The error body indicates "missing parameter".  Perhaps the intent was for `https://${session.shop}/admin/metafields.json` to be a GET (Method.Get)?

**Comment by pratiknikam** [comment]
I have similar question, I'm seeing ton of 400 on production and when I checked stack trace, they are originating from same location as pointed above: https://github.com/Shopify/koa-shopify-auth/blob/master/src/verify-request/verify-token.ts#L21
