### ISSUE TITLE
error in my custom session after updating to 5.0.3

### ISSUE THREAD

**Issue by ironda2020** [Shopify/koa-shopify-auth#153]
# Issue summary
after updating koa-shopify-auth from **4.1.4** to **5.0.3** my custom session does not work anymore 

**Shopify.Context.initialize({
  API_KEY: process.env.SHOPIFY_API_KEY,
  API_SECRET_KEY: process.env.SHOPIFY_API_SECRET,
  SCOPES: process.env.SHOPIFY_API_SCOPES.split(","),
  HOST_NAME: process.env.HOST.replace(/https:\/\/|\/$/g, ""),
  API_VERSION: process.env.API_VERSION,
  IS_EMBEDDED_APP: true,
  SESSION_STORAGE: new Shopify.Session.CustomSessionStorage(
    storeCallBack,
    loadCallBack,
    deleteCallBack
  ),
});**

## Expected behavior

my custom session should still work fine

## Actual behavior

I get this error:
<details>   InternalServerError: OAuth Session could not be deleted. Please check your session storage functionality.
      at Object.throw (C:\myApps\ir-app\node_modules\koa\lib\context.js:97:11)
      at C:\myApps\ir-app\node_modules\@shopify\koa-shopify-auth\dist\src\auth\index.js:107:42
      at step (C:\myApps\ir-app\node_modules\tslib\tslib.js:141:27)
      at Object.throw (C:\myApps\ir-app\node_modules\tslib\tslib.js:122:57)
      at rejected (C:\myApps\ir-app\node_modules\tslib\tslib.js:113:69)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)</details>

## Steps to reproduce the problem

1. updating koa-shopify-auth from **4.1.4** to **5.0.3**

**Comment by ironda2020** [comment]
if i go back to 4.1.4 everything works fine but the shopify partner informs me that:
My app is using an older version of either the shopify_app gem or @shopify/koa-shopify-auth library that has called the deprecated Embedded App SDK (EASDK) within the last 10 days.
You must update this app to use either shopify_app [v18.1.1 (https://github.com/Shopify/shopify_app/blob/master/docs/Upgrading.md) or @shopify/koa-shopify-auth [v5.0.3](https://github.com/Shopify/koa-shopify-auth/blob/master/CHANGELOG.md). Updating will replace these EASDK calls with App Bridge.

**Comment by assaflei** [comment]
I'm not getting the same exact error but on my implementation I saw that using Context on [this line](https://github.com/Shopify/koa-shopify-auth/blob/15379030fd1677f4a37a215d080c19f3244047cd/src/auth/create-request-storage-access.ts#L49) returns an empty string despite using the Shopify.Context.initialize command.
It looks like the koa object uses a different context object...

Using shopify-api 2.1.0
koa-shopify-auth 5.0.3

**Comment by ironda2020** [comment]
Hi @Asadmasood195
no solution for the moment! I returned back to 4.1.4 version while waiting for the people who made this update to give us a feedback.
Thank you all

**Comment by pratiknikam** [comment]
I believe you see following warning in your partner dashboard but despite reverted to older version to stay operational.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/2853953/156682832-27b05be9-90eb-4c39-a134-7c7b544a39e6.png">

**Comment by ironda2020** [comment]
Yes exactly @pratiknikam

**Comment by technologytesting** [comment]
Same here. Switched to 5.0.3 & started having issues with the uninstall webhook as well as general oAuth process. I've reverted back to v4.1.2 for time being while I figure out how to be operational with 5.0.3.
