### ISSUE TITLE
Cookies on domain causing infinite loop ?

### ISSUE THREAD

**Issue by psppro26** [Shopify/koa-shopify-auth#156]
Hello, i'm using Tawk.to chat app on my shopify app,so basically the app is adding a cookie to follow customers.

Right now i have an issue with the auth of my shopify embedded app, who get a loop when i'm restarting my node server ! 
<img width="1083" alt="Capture d’écran 2022-03-10 à 18 14 24" src="https://user-images.githubusercontent.com/25665778/157727493-e805ae8e-c10f-44b6-adf8-83c2e55b6abe.png">

I know it's due to that cookie , cause when i remove it, it's instant work and redirect perfectly , then it's working until i restart the node server.

I tried on Safari / Firefox and it's working perfectly , issue is only on Google Chrome !

any idea why is it happening ?

**Comment by haripraneshHP** [comment]
I'm facing the same issue

**Comment by gokulakkrishnan** [comment]
I'm facing the same issue. Anyone have solution for this?

**Comment by psppro26** [comment]
Found a solution by myself :-) Basically just remove every cookies who's conflicting on client side ;-)

```
router.get("/", async ctx => {
    const shop = ctx.query.shop;
  

    ctx.cookies.set("cookieNAME", "", {
          httpOnly: false,
          secure: true,
          sameSite: "none",
          domain: ".domain.com"
        });
        ctx.cookies.set("cookieName", "", {
          httpOnly: false,
          secure: true,
          sameSite: "none"
        });
```
