### ISSUE TITLE
Offline access token is expiring after some time and no longer works

### ISSUE THREAD

**Issue by rafaelsorto** [Shopify/koa-shopify-auth#169]
# Issue summary

Write a short description of the issue here ↓

We are using the createShopifyAuth middleware to authenticate our apps and are specifying the accessMode: 'offline' in the app settings. Somehow the accessToken received in the callback is expiring for some shops and we are no longer able to do calls to the Shopify Rest API.

## Expected behavior

The offline access tokens should not expire if the app has not been uninstalled from the Shopify Store.

## Actual behavior

The access token expires and they are no longer valid as seen in the Shopify API response message like:

```
{
    "errors": "[API] Invalid API key or access token (unrecognized login or wrong password)"
}
```

## Steps to reproduce the problem

1. Create an app with the koa-shopify-auth middleware
2. Setup the app to use the createShopify auth flow like the following:
```
server.use(
  createShopifyAuth({
    accessMode: "offline",
    async afterAuth(ctx) {
      // Access token and shop available in ctx.state.shopify
      const { shop, accessToken, scope } = ctx.state.shopify;
```
3. Save the accessToken in somewhere you can use later. And check if the code still works. In many cases the code no longer works.

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by Utkarsh85** [comment]
Could you figure a solution to this @rafaelsorto
