### ISSUE TITLE
App using createShopifyAuth from @shopify/koa-shopify-auth cannot be installed when app is using prefix

### ISSUE THREAD

**Issue by alozytskyi** [Shopify/koa-shopify-auth#19]
`prefix = "/"` default  in  this file:

https://github.com/Shopify/koa-shopify-auth/blob/eb2932c700fedbef32fc9eb4e44fc801a37b1541/src/auth/client/request-storage-access.ts#L2

Is causing infinite redirect when prefix does not end with a trailing `/`, however in other code default prefix is `""` and forces user to configure prefix without trailing `/`

Basically this makes it impossible to install from path like `/a/b/app` or alike

**Comment by skoulix** [comment]
Same issue as well.

**Comment by alozytskyi** [comment]
@sirrodgepodge can you please apply your fix to this new repo?

**Comment by skoulix** [comment]
Does anyone has a fix for this. It's technically impossible to use a prefix, if you do so it goes on an endless redirection loop.

**Comment by tanema** [comment]
Will be fixed in the next release because of #29

**Comment by deldrid1** [comment]
@tanema - when can we get a release for this?  Its been nearly 3 weeks since the PR was merged.

**Comment by leventecsordas** [comment]
@mkevinosullivan @atesgoral 

do you have a timeline on when this fix it will be released?

**Comment by mkevinosullivan** [comment]
There are a few commits in `master` that do indeed need to be released.  However, we're currently holding off on releasing a new version until after Cyber-Monday, to avoid potentially impacting thousands of apps before BFCM.

So expect it to release around Dec 2.

**Comment by mkevinosullivan** [comment]
v3.2.0 released today, which includes #29
