### ISSUE TITLE
Can not get online access token

### ISSUE THREAD

**Issue by babkenmes** [Shopify/koa-shopify-auth#20]
## Overview
I am using [`@shopify/koa-shopify-auth`](https://github.com/Shopify/quilt/tree/master/packages/koa-shopify-auth#shopifykoa-shopify-auth) and need to implement online access mode authorization flow, I set accessMode to online but still get offline access token which does not contain associated_user data described in Shopify [docs](https://shopify.dev/tutorials/authenticate-with-oauth#step-3-confirm-installation) 

    shopifyAuth({
      apiKey: SHOPIFY_API_KEY,
      secret: SHOPIFY_API_SECRET,
      scopes: ['write_products'],
      accessMode: 'online',
      afterAuth(ctx) {
        const {shop, accessToken} = ctx.session;
        
        console.log('We did it!', accessToken);

        return ctx.redirect('/');
      },
    }),
  

![screenshot](https://user-images.githubusercontent.com/28057877/86271891-c2968680-bbde-11ea-8758-f178c5722f07.png)

Please, correct me If I am doing something wrong.

**Comment by kevinpjones** [comment]
Seems to me this duplicates Shopify/quilt#1420 ... for which there's been a pull request ready for some time.

**Comment by thecodepixi** [comment]
Hi 👋🏻  This issue is likely resolved by the most recent version(s) of this lib, so I'm going to go ahead and close this. If an issue getting access tokens still persists, please open a new issue. Thanks!
