### ISSUE TITLE
Allow users to access app outside shopify store

### ISSUE THREAD

**Issue by cedriclajato** [Shopify/koa-shopify-auth#24]
Thank you for this great module. But is it possible to allow my users to access my app on embedded app and outside shopify too?

**Comment by Resousse** [comment]
Hello, Does it mean your application is static and doesn't need to use the store Token to fetch the shop data? Thanks

**Comment by tanema** [comment]
To my knowledge, this library has no restrictions that require you to be embedded in shopify admin. Your users should be able to access your site on shopify and on your own domain
