### ISSUE TITLE
Is it possible to release a new version ?

### ISSUE THREAD

**Issue by gregorybesson** [Shopify/koa-shopify-auth#33]
Hello Here and thanks for your work,

Would it be possible to release a new version from the master branch (to add these commits in the distrib:
https://github.com/Shopify/koa-shopify-auth/compare/v3.1.72...master )

Particularly, I think that the addition of the missing user data to KOA auth is a must have

Thanks a lot,
Greg

**Comment by mkevinosullivan** [comment]
Hi Greg,

There are a few commits in `master` that do indeed need to be released.  However, we're currently holding off on releasing a new version until after Cyber-Monday, to avoid potentially impacting thousands of apps before BFCM.

Regards,
Kevin.
