### ISSUE TITLE
Redirect Loop in Safari

### ISSUE THREAD

**Issue by chris8447** [Shopify/koa-shopify-auth#36]
I'm currently facing a redirect loop when my Shopify app starts the authentication process in Safari. Due to Safari's new policy where they block 3rd party cookies you can only get around by accessing Storage Access. Koa-Auth is already addressing this and prompts the user to accept. While this solution worked for some time it is not anymore. 

Is someone else also experiencing this behavior? Can we expect any bugfix for this in the near future?

Thanks,
Chris

**Comment by hrstrand** [comment]
Chris,

I am facing same issue, and there is not a clear path away from this issue from Shopify yet.

Currently, I am experimenting with 

https://github.com/nprutan/shopify-cookieless-auth-demo

it seems to actually work fine, once you implement setting and getting the tokens from backend db

/peter

**Comment by chris8447** [comment]
Hi Peter,
I saw it already. It replaces cookies with the session token approach.

I will try it myself and give feedback. 

Chris

**Comment by skoulix** [comment]
i've implemented many solutions that exists out there including this specific package and the cookieless unofficial one you're suggesting. None worked 100% for me and it was only causing issues and headaches, endless redirects at Safari, problems with the prefix and the trailing slash (I saw this was fixed at a new release today).

Do yourselves a favor and save valuable time by implementing the new way that Shopify suggests here https://shopify.dev/tutorials/authenticate-your-app-using-session-tokens 
It seems difficult at first but once you grasp it everything will work like a charm. Let me know if anyone of you needs any help. 

Evan

**Comment by avcohen** [comment]
> I've implemented many solutions that exists out there including this specific package and the cookieless unofficial one you're suggesting. None worked 100% for me and it was only causing issues and headaches, endless redirects at Safari, problems with the prefix and the trailing slash (I saw this was fixed at a new release today).
> 
> Do yourselves a favor and save valuable time by implementing the new way that Shopify suggests here https://shopify.dev/tutorials/authenticate-your-app-using-session-tokens
> It seems difficult at first but once you grasp it everything will work like a charm. It works for Ruby apps, React or even custom Node.js ones. Actually I managed to get it working at a custom app based entirely on Nuxt.js.
> Let me know if anyone of you needs any help.
> 
> Evan

I'd be curious to see your implementation for the react / nuxt app — i'm working on a next.js app and started to use [this repo](https://github.com/capsule-corp/now-shopify-auth) but I believe it falls victim to these same issues.

Thanks,

A

**Comment by skoulix** [comment]
@avcohen

I can't share the source code of the app since it's a commercial one and already live at the Shopify app store. Having said that I can help you with anything you want and any queries you may have. My app is based on Vue.js and Nuxt.js but the logic is the same with your app which as far as I can tell is based on React and Next.js. I don't think the implementation differs to a great extend, different frameworks, same logic.

Please email me directly and I would be happy to assist you.

**Comment by avcohen** [comment]
@skoulix — That's mighty kind of you. I did end up finding a solid solution using [this repo](https://github.com/ctrlaltdylan/shopify-nextjs-toolbox). Seems like a good starting point!

**Comment by skoulix** [comment]
> @skoulix — That's mighty kind of you. I did end up finding a solid solution using [this repo](https://github.com/ctrlaltdylan/shopify-nextjs-toolbox). Seems like a good starting point!

No problem. Glad you found a solution. 
Happy coding :-)

**Comment by harishannam** [comment]
Disabling forceRedirect on your Provider config would prevent the looping issue but not sure what would be the side effects. 

In this case, if it is unable to embed the app inside the iframe, it will redirect to open it separately.
