### ISSUE TITLE
@koa-shopify-auth: createShopifyAuth prefix is killing two birds with one stone

### ISSUE THREAD

**Issue by adiled** [Shopify/koa-shopify-auth#37]
I wouldn't write a story or detail anything. I have gone in circles with the whole existing stack provided by shopify only because I chose not to use top level domain for app.

Pretty much all the issues here are coming from impractical assumptions made on `prefix` option accepted by `createShopifyAuth`.

Currently, the oAuth paths constructed using `prefix` are then being compared with `ctx.path` for redirect logic, but `ctx.path` is almost always relative in deployments behind a proxy.

`ctx.originUrl` could be used, right now my head is a centrifuge, I will add more to this once I am over hacking around my deployments and get an indication that this middleware being used in CLI generated ~~product~~ codebase is not as orphan as it seems to be.

Oh and for TLDR, this is resulting in bad redirections, redirect loops, broken in-app view, cookie issues, callback url glitch and countless reported issues with wrong diagnostics.

**Comment by Steven4294** [comment]
+1
