### ISSUE TITLE
Could you please add MIT License

### ISSUE THREAD

**Issue by bogeyorpar** [Shopify/koa-shopify-auth#38]
# Issue summary

The MIT License link in the Readme.md is linking to a non-existent file

## Expected behavior

Should display the MIT license

## Actual behavior

404 error

## Steps to reproduce the problem

1. In the Readme.md, click on the MIT License link

## Reduced test case

This is the link it tries to display but does not exist
https://github.com/Shopify/koa-shopify-auth/blob/HEAD/LICENSE.md

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by andyw8** [comment]
@bogeyorpar thanks for the report, this has been addressed.
