### ISSUE TITLE
createShopify middleware is not getting called on firebase functions after deploying it

### ISSUE THREAD

**Issue by shivgodi7** [Shopify/koa-shopify-auth#42]
The createShopify middleware is not getting called on firebase functions after deploying it.
But it works well on local emulator.
Any idea how to make this middleware createShopifyAuth() called ?
Thank you,

  const { default: createShopifyAuth } = require('@shopify/koa-shopify-auth');
  const server = new Koa();
  server.use(session({ secure: true, sameSite: 'none' }, server));
  server.keys = [API_SECRET_KEY];
  server.use(
    createShopifyAuth({
      apiKey: API_KEY,
      secret: API_SECRET_KEY,
      scopes: ['read_p'],
      afterAuth(ctx) {
        ctx.redirect('/');
      },
    })
  )

**Comment by KevinSig** [comment]
Hi shivgodi7 any workaround you were able to find?
