### ISSUE TITLE
associated_user is inaccessible if accessMode is offline

### ISSUE THREAD

**Issue by konrain** [Shopify/koa-shopify-auth#46]
# Issue summary
associated user is inaccessible if accessMode is 'offline',

# Write a short description of the issue here ↓

#23 added associated user to the session, but its inaccessible if accessMode is set to 'offline'

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by mkevinosullivan** [comment]
There is no user associated with 'offline' access mode, hence that data is unavailable. https://shopify.dev/concepts/about-apis/authentication#offline-access
