### ISSUE TITLE
Api Versions are out of date

### ISSUE THREAD

**Issue by furnaceX** [Shopify/koa-shopify-auth#57]
# Issue summary

I am using this as specified in the "Usage" section, by also including `import Shopify, {ApiVersion} from '@shopify/shopify-api';`
When I print out the available ApiVersions, I get an old list:
```
ApiVersions: {
  July19: '2019-07',
  October19: '2019-10',
  January20: '2020-01',
  April20: '2020-04',
  July20: '2020-07',
  October20: '2020-10',
  Unstable: 'unstable',
  Unversioned: 'unversioned'
}
```

Seems that these are cached values.  How do I get the latest API versions to load?

I would post this in the shopify-api github, but that seems to be a Ruby repo, so I didn't think it was appropriate to ask there.

------------------

super confusing... there is a package called `shopify_api` and one called `@shopify/shopify-api`. The later is NOT ruby, so I'll post there.

**Comment by paulomarg** [comment]
As we discussed on https://github.com/Shopify/shopify-node-api/issues/116, this was indeed missing the latest version. It was updated and will be available in the upcoming release.

Closing this since it is essentially a duplicate.
