### ISSUE TITLE
Offline mode - Endless redirects

### ISSUE THREAD

**Issue by rac146** [Shopify/koa-shopify-auth#58]
# Issue summary

When using v4 and setting accessMode 'offline', after a successful authentication the application will not redirect properly to the application home page. Instead it redirects to the 'fallbackRoute' and starts performing endless redirects to itself.

## Expected behavior

Prior to v4, accessMode 'offline' still loaded the application correctly after authentication. Should we be using online mode exclusively now and then requesting an offline token separately after a successful authentication?

**Comment by paulomarg** [comment]
Hi @rac146, there is currently an issue with offline mode, we're working on a fix!

**Comment by paulomarg** [comment]
We've released v4.0.2 which should fix this issue.

**Note:** if you're using `verifyRequest`, please make sure that you're calling `verifyRequest({accessMode: 'offline'})` to ensure it works for offline tokens.
