### ISSUE TITLE
Create utility function to tell whether an AccessMode is online / offline

### ISSUE THREAD

**Issue by paulomarg** [Shopify/koa-shopify-auth#60]
## Overview

We currently check if `AccessMode === 'online'` in several places in the code. We could extract those checks into a shared method, in possibly a new `utilities` project folder, where we can gather values that are common to both `shopifyAuth` and `verifyRequest`.

We should also consider changing the `AccessMode` type into an `enum` so we don't have to rely on the actual string values in the code.

## Type

- [ ] New feature
- [X] Changes to existing features

## Motivation

This is mostly to make maintenance easier, and to ensure that we have consistent code style / behaviour around `AccessMode` values.

## Checklist

- [X] Please delete the labels section before submitting your issue
- [X] I have described this feature request in a way that is actionable (if possible)

**Comment by akhilmhdh** [comment]
@paulomarg Is this issue still open. I would like to do this issue, if its still open.

**Comment by paulomarg** [comment]
Hey @akhilmhdh, we haven't gotten around to this one yet, so it's up for grabs. If you're able to do this, we'd appreciate your contribution!

**Comment by akhilmhdh** [comment]
@paulomarg ohh great. Would love to. Then ill work on it. Please assign it to me.
