### ISSUE TITLE
Importing @shopify/koa-shopfy-auth crashes the server with no error message

### ISSUE THREAD

**Issue by Twiggeh** [Shopify/koa-shopify-auth#67]
# Issue summary

Importing 
```js
import createShopifyAuth, { verifyRequest } from '@shopify/koa-shopify-auth';
```

throws this in tsc, and the server crashes
```
node_modules/@shopify/koa-shopify-auth/dist/src/verify-request/types.d.ts(1,28): error TS2307: Cannot find module 'src/types' or its corresponding type declarations.
```
![image](https://user-images.githubusercontent.com/23149166/110965540-91b54680-8354-11eb-899e-372d34ad21a5.png)

## Expected behavior

Shouldn't crash :D

## Actual behavior

Crahses

## Simple Fix:

```js
import createShopifyAuth from '@shopify/koa-shopify-auth';

const { verifyRequest } = createShopifyAuth; 

import ShopifyMaster, { ApiVersion } from '@shopify/shopify-api';

const Shopify = ShopifyMaster.default;
```

## Steps to reproduce the problem

1. git clone `https://github.com/Twiggeh/koa-shopify-auth-report.git` 
2. `cd koa-shopify-auth-report/server && yarn install && yarn debug`
(Seperate Terminal)
3. `cd koa-shopify-auth-report/server && node ./dist/app.js`

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
Hey @Twiggeh, thanks for this! It was a broken import in the `verify-request/types.ts` file that caused this. It was fixed in https://github.com/Shopify/koa-shopify-auth/pull/63!
