### ISSUE TITLE
Navigation to enable_cookies page when using session token 

### ISSUE THREAD

**Issue by assaflei** [Shopify/koa-shopify-auth#93]
# Issue summary

I was using the [node react guide](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/embed-your-app-in-shopify) to create a new app.

During authentication I noticed that the flow includes navigation to the enable_cookies page
While quickly leaving the page I think that seeing it during the process is not an expected behavior taking into account that cookies are not being used anymore

## Expected behavior

The login flow should not include enable_cookies page

## Actual behavior

The login flow includes enable_cookies page
See below network tab from browser

![image](https://user-images.githubusercontent.com/15898926/114508406-fd811c80-9c3c-11eb-9f84-763bd426ba9e.png)

## Steps to reproduce the problem

Follow the [guide](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/embed-your-app-in-shopify) and execute the app. Trace the navigated pages

## Reduced test case

---

## Checklist

- [ x] Please delete the labels section before submitting your issue
- [ x] I have described this issue in a way that is actionable (if possible)

**Comment by pratiknikam** [comment]
This is expected behavior as per https://github.com/Shopify/koa-shopify-auth/issues/81#issuecomment-816656683
